[package]
name = "finance_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
invoice_manager = {path = "../invoice_manager"}
clap = { version = "4.5.42", features = ["derive"] }
tabled = "0.20.0"
tokio = { version = "1.47.1", features = ["full"] }